[tools]
node = "24"
python = "3"
ghq = "latest"
glow = "latest"
tmux = "latest"
bat = "latest"
"npm:netlify-cli" = "latest"
"npm:aws-cdk" = "latest"
"pipx:httpie" = "latest"
"github:gastownhall/beads" = "1.2.2"
